//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class education
    {
        public int educationID { get; set; }
        public string tittle { get; set; }
        public string subtittle { get; set; }
        public string subtittle2 { get; set; }
        public string gradeavarage { get; set; }
        public string date { get; set; }
    }
}
