//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class social
    {
        public int meidaID { get; set; }
        public string mediaName { get; set; }
        public string mediaLink { get; set; }
        public string mediaIcon { get; set; }
        public Nullable<bool> mediaStatus { get; set; }
    }
}
